#-----------------------
# Wemake Python Lint
#
# Boris Zhenikhov
# 21 April 2021
#-----------------------

name: wemake-python-lint

on: push

jobs:
  wemake-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: make lint